name: Java CI with Maven

on:
  push:
    branches:
      - main
      - testing
  pull_request:
    branches:
      - main
      - testing

permissions:
  contents: write
  security-events: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build Maven project
      run: mvn install

   
